spring.application.name=Internal_flag_manager
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/FeatureDB

# Your PostgreSQL username and password.
# (The default is often 'postgres' for both if you just installed it).
# (If using Docker, this is what you set in docker-compose.yml).
spring.datasource.username= postgres
spring.datasource.password= Xolotlitz$38531
spring.jpa.hibernate.ddl-auto=update
